### ISSUE TITLE
download stuck and not starting

### ISSUE THREAD

**Issue by devsheva** [CarrotRub/Fit-Launcher#13]
i see like download is in pause and even pressing some times the play, it doesn't start. already tried to switch network, close the app and restart it but nothing

**Comment by CarrotRub** [comment]
Have you tried to search for the game and click on install button again and follow the steps, it should work.

**Comment by devsheva** [comment]
ok it worked out, but download is very slow, like 0.15MiB/s, and that's not my actual mbps

**Comment by CarrotRub** [comment]
When it first starts it is slow but it goes up with time the other possibility is just that there isn't any seeders.

What are your specs and what is the game you are trying to download ?

**Comment by devsheva** [comment]
cpu: ryzen 7 3700x
16GB RAM DDR4 3200 MHz
Nvidia RTX 3060
100Mbps band

i'm trying to download GOW Ragnarok

**Comment by devsheva** [comment]
> is just that there isn't any seeders.
maybe a feature could be adding a seeders counter info

**Comment by CarrotRub** [comment]
For GOW ragnarok it's just low number of seeders, yes this seems like a nice feature that I can implement quickly, I will do.

**Comment by devsheva** [comment]
Nice, thank you. I hope number of seeders will increase soon
