### ISSUE TITLE
Error parsing game data

### ISSUE THREAD

**Issue by sorcho** [CarrotRub/Fit-Launcher#21]
As the title say, I can't use the launcher since it doesn't show any games.
Just installed from the Releases tab, but it doesn't seem to work.

Attached screenshot:
![Screenshot 2024-10-13 085847](https://github.com/user-attachments/assets/4aa1d982-11ef-479f-a9fc-d8706c43a5cd)

FitLauncher version: 1.0.3
Windows 11 23H2

**Comment by CarrotRub** [comment]
Are you in Italy ?
If yes, use a VPN.

**Comment by sorcho** [comment]
> Are you in Italy ? If yes, use a VPN.

It loads the main pagewith a VPN but now it can't seem to start a download.
Why isn't it availabe in Italy tho?

**Comment by CarrotRub** [comment]
Italy blocked Fitgirls Repack Website.
Some VPN (such as ProtonVPN free) can sometimes block P2P.
