### ISSUE TITLE
Error after cancelling a game

### ISSUE THREAD

**Issue by antnjhn** [CarrotRub/Fit-Launcher#22]
I tried to test this program and clicked download but after a few seconds ,i turned off the download thinking it mustve stopped downloading the game now 1.7 gb repack file is in the directory.

**Comment by CarrotRub** [comment]
It pre-allocates the necessary space before downloading.
For example if you download a 3gB game, it will create all the files that adds up to 3gB then starts download so that if there isn't enough space it will directly say so without doing any weird math.
