### ISSUE TITLE
Regarding UI

### ISSUE THREAD

**Issue by Moosetache1** [CarrotRub/Fit-Launcher#3]
![FIT LAUNCHER 1](https://github.com/user-attachments/assets/eca28c1e-a605-401a-bdd9-712ecabb6246)
![fit launcher 2](https://github.com/user-attachments/assets/52c9e60a-1e45-4722-b919-e5340311f7b6)
 Launcher keeps showing nan% is downloading and also can't get out of game selection once i click on a game to check out description

**Comment by CarrotRub** [comment]
When it shows NaN% it just means that nothing is downloading, for the game selection click on the title of the game.
