### ISSUE TITLE
Can t download games progress  Fit Launcher 

### ISSUE THREAD

**Issue by popcorn2024ok** [CarrotRub/Fit-Launcher#30]
![17295516184657917459723224482250](https://github.com/user-attachments/assets/5dc50d24-4c19-4f4b-b37a-a7cabc7cdce8)

Can't download games progress is showing and games won't download Fit Launche version 1.0.4

**Comment by CarrotRub** [comment]
Which game and how many peers are there ?

**Comment by popcorn2024ok** [comment]
> Which game and how many peers are there ?

In almost all games it does not let me download any in Fit Launcher

**Comment by carlossclaro** [comment]
@popcorn2024ok, please confirm if you are using a VPN or not. 

If you are using the free version of ProtonVPN, P2P is disabled and downloads will not start.

**Comment by carlossclaro** [comment]
@CarrotRub, please close due to no response.
