### ISSUE TITLE
App is just not opening. 

### ISSUE THREAD

**Issue by goranbalsic** [CarrotRub/Fit-Launcher#33]
When I run it, as Admin, it just doesn't open, with no error.
I have updated everything. 

Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   1.38 GHz
Installed RAM	16.0 GB (15.7 GB usable)

**Comment by CarrotRub** [comment]
Can you send the latest part of the logs if possible it is found in `AppData\Roaming\com.fitlauncher.carrotrub\logs\app.log`.

**Comment by goranbalsic** [comment]
Sure, here it is.
It's empty.
[app.log](https://github.com/user-attachments/files/17573972/app.log)

**Comment by CarrotRub** [comment]
If it's empty maybe check if your AV hasn't quarantined it.

**Comment by goranbalsic** [comment]
No AV, I run Ghost Spectre win 10.

**Comment by CarrotRub** [comment]
I never tested it on Ghost Spectre Win 10, I have no idea if it can have issues with my app

**Comment by DopamineSource** [comment]
same issue. install app using the msi installer to secondary external hard drive, open it, nothing happens. log is empty. no antivirus

**Comment by CarrotRub** [comment]
Do you also have Ghost Spectre Win 10?

**Comment by DopamineSource** [comment]
no i dont. regular windows install with minimal debloating. (uninstalled some windows apps and such. updates and defender intact)

**Comment by CarrotRub** [comment]
Try the newest 2.0 version, it should be fixed

**Comment by goranbalsic** [comment]
Thank you, this fixed it, this is amazing. Merry Chrismas.

**Comment by CarrotRub** [comment]
Merry Christmas to you too my friend <3
