### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by NeKoOuO** [CarrotRub/Fit-Launcher#9]
I am interested in helping with the translation of this project into another language

**Comment by CarrotRub** [comment]
For this we would need to find a library that acts like i18n and is still being updated for solidjs or we would have to create our own, if you know any library that may do this and is not archived, please tell us 👍🏻

**Comment by CarrotRub** [comment]
I will use the Solid Primitive [i18n](https://primitives.solidjs.community/package/i18n/) , it will be added soon.

**Comment by NeKoOuO** [comment]
Any update here?

**Comment by NeKoOuO** [comment]
Any update here?
